# Generated by Django 3.0.7 on 2020-06-13 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('users_fullname', models.CharField(blank=True, max_length=50)),
                ('password', models.CharField(max_length=90)),
                ('users_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'apps_users0',
                'managed': True,
            },
        ),
    ]
